namespace = TexDebugger

; Texture Slot Debugger for 3DM based modding.
;
; Requirements: ---------------------------------------------------------------------------
; - draw_2d.hlsl in the same folder as this ini.
;
;
; Usage: ----------------------------------------------------------------------------------
;
; Add the following to your ini file section to debug:
;
; (For texture debugging)
; run = CommandList\TexDebugger\TextureDebugger
; run = CommandList\TexDebugger\Tex
;
; (For render target/depth buffer debugging)
; run = CommandList\TexDebugger\Outputs
; run = CommandList\TexDebugger\Out
;
; F10 to reload mods and then press ALT+F12 to toggle the debugger on/off.
; When the debugger is on there will be an overlay with the textures on top of your game.
;
; The order of textures displayed is as follows:
; ps-t0, ps-t1, ps-t2, ps-t3,
; ps-t4, ps-t5, ps-t6, ps-t7,
; ps-t8, ps-t9,ps-t10, ps-t11
;
; In the case of outputs, the order is as follows:
;
; o0, o1, o2, o3,
; o4, o5, o6, o7,
; oD

[Constants]
global $enabled = 0

[KeyToggle]
key = ALT F12
type = cycle
$enabled = 0, 1

[Present]
if $enabled == 1
	run = CommandListDebug
endif

[CommandListTex]
run = CommandListTextures

[CommandListTextures]
ResourcePST0 = ref ps-t0
ResourcePST1 = ref ps-t1
ResourcePST2 = ref ps-t2
ResourcePST3 = ref ps-t3
ResourcePST4 = ref ps-t4
ResourcePST5 = ref ps-t5
ResourcePST6 = ref ps-t6
ResourcePST7 = ref ps-t7
ResourcePST8 = ref ps-t8
ResourcePST9 = ref ps-t9
ResourcePST10 = ref ps-t10
ResourcePST11 = ref ps-t11

[CommandListOut]
run = CommandListOutputs

[CommandListOutputs]
ResourcePST0 = ref o0
ResourcePST1 = ref o1
ResourcePST2 = ref o2
ResourcePST3 = ref o3
ResourcePST4 = ref o4
ResourcePST5 = ref o5
ResourcePST6 = ref o6
ResourcePST7 = ref o7
ResourcePST8 = ref oD

[CommandListDebug]
Resource\GIMIv8\Text = ref ResourceDEBUGGERON
Resource\GIMIv8\TextParams = ref ResourceTextParams
run = CommandList\GIMIv8\PrintText
; x87 width
; y87 height
; z87 position x
; w87 position y
local $x87bak = x87
local $y87bak = y87
local $z87bak = z87
local $w87bak = w87
local $size = 0.15
local $voffset = 0.05
local $hoffset = 0.05
x87 = $size
y87 = $size * 16 / 9
z87 = $hoffset
w87 = $voffset
ps-t100 = ref ResourcePST0
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST1
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST2
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST3
run = CustomShaderSquare
z87 = $hoffset
w87 = w87 + y87 + $voffset
ps-t100 = ref ResourcePST4
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST5
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST6
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST7
run = CustomShaderSquare
z87 = $hoffset
w87 = w87 + y87 + $voffset
ps-t100 = ref ResourcePST8
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST9
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST10
run = CustomShaderSquare
z87 = z87 + x87 + $hoffset
ps-t100 = ref ResourcePST11
run = CustomShaderSquare
x87 = $x87bak
y87 = $y87bak
z87 = $z87bak
w87 = $w87bak

[CustomShaderSquare]
hs = null
ds = null
gs = null
cs = null
run = BuiltInCommandListUnbindAllRenderTargets
vs = draw_2d.hlsl
ps = draw_2d.hlsl
; blend = ADD SRC_ALPHA INV_SRC_ALPHA
cull = none
topology = triangle_strip
o0 = set_viewport bb
Draw = 4, 0

[ResourcePST0]

[ResourcePST1]

[ResourcePST2]

[ResourcePST3]

[ResourcePST4]

[ResourcePST5]

[ResourcePST6]

[ResourcePST7]

[ResourcePST8]

[ResourcePST9]

[ResourcePST10]

[ResourcePST11]

[ResourceDEBUGGERON]
type = Buffer
data = "TEXTURE DEBUGGER ON"

[ResourceTextParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT -1.0 -0.95 +1.0 -0.95 1.0 0.0 0.0 1.0 0 0.0 0 0.95 0.020 0.020 2 3 0 1.0
;                ^Bounds Rectangle^| ^^^Colour^^^^   |Background  | ^Border^^| ^ ^ | ^ | ^-- font scale
;                x1    y1   x2 y2  | r    g b    a   |r g b a     | horz vert|  ^  | ^------ text alignment: 0=left 1=center 2=right
;                   range -1:+1    |                 |            |          |  ^----------- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom
